### ISSUE TITLE
关于地图西沙群岛

### ISSUE THREAD

**Issue by EdikWang** [MarkingCode/jsMap#1]
可不可以在西沙群岛添加点小点，展示一下各岛屿！

**Comment by MarkingCode** [comment]
您好，感谢您的反馈。由于 jsMap 中用到的所有地图数据均来自于网络搜集，而并非作者自行绘制，因此对于未搜集到的区域无法进行绘制。

**Comment by EdikWang** [comment]
好的，谢谢，我看看自己能不能画一下！
