### ISSUE TITLE
怎么适配移动端呢？

### ISSUE THREAD

**Issue by makenum** [MarkingCode/jsMap#3]
地图需要适配移动端，vw和js控制100%，地图会截掉一部分，是什么原因呢？

**Comment by MarkingCode** [comment]
您好，感谢您的反馈。
目前，jsMap 只兼容桌面端浏览器，并未对移动端做适配；
截止到 v4.0.0 ，在设置地图时始终需要明确设定宽度，设置成 100% 可能会出现问题；
不过，在即将发布的新版本中，将会支持 100% 的宽度设置。
